name: ros2

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ ros2, ros2-devel ]
  pull_request:
    branches: [ ros2, ros2-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ros2-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - humble
          - rolling
        include:
            # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
            ros_distribution: foxy
            ros_version: 2
            # Galactic Geochelone (May 2021)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
            ros_distribution: galactic
            ros_version: 2
            # Humble Hawksbill (May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
            # Rolling
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: dynamixel_workbench
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "https://raw.githubusercontent.com/ROBOTIS-GIT/dynamixel-workbench/ros2-devel/.github/workflows/dynamixel_workbench.repos"
