name: ros2-ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ ros2, ros2-devel ]
  pull_request:
    branches: [ ros2, ros2-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ros2-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          # - rolling
        include:
          - docker_image: ubuntu:focal
            ros_distribution: foxy
            ros_version: 2
          - docker_image: ubuntu:focal
            ros_distribution: galactic
            ros_version: 2
          # - docker_image: ubuntu:jammy
          #   ros_distribution: rolling
          #   ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Setup ROS2 environment
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: dynamixel_workbench
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
